<div class="container">
    <div class="col-lg-12">
        <h1>
            <?php echo $article->title ?>
            <small></small>
        </h1>
        <p class="description"><span class="glyphicon glyphicon-time"></span> Posted  <?php echo $article->updated_at->format('l jS \of F Y h:i:s A'); ?>
            <?php if(isset($article->author->usrName)): ?>
            by <?php echo $article->author->usrName ?></p>
        <?php endif; ?>
        <hr>
    </div>
    <div class="row">
        <div class="col-lg-8">
            <?php if(!empty($video)): ?>
                <iframe src="http://embed.redtube.com/?id=<?php echo $video->video->video_id ?>&bgcolor=000000" frameborder="0" width="100%" height="560" scrolling="no" allowfullscreen></iframe>
                <?php foreach($video->video->tags as $tag): ?>
                    <span class="label label-default"> <?php echo $tag ?></span>
                <?php endforeach ?>
                <hr>
            <?php endif; ?>
            <div class="description"><?php echo $article->introduction ?></div>
            <div class="description">
            <?php echo $article->description ?>
            </div>
            <hr>
            <ul>
                <?php foreach ($flashMessages as $msg) : ?>
                    <li><?php echo $msg; ?></li>
                <?php endforeach; ?>
            </ul>
            <form role="form" action="<?php echo $this->url('comment', array('action' => 'submit')); ?>" method="post">
                <input type="hidden" value="<?php echo $article->id ?>" name="article">
                <?php $user = $this->identity() ?>
                <?php if(is_null($user)): ?>
                    <div class="form-group">
                        <div class="input-group input-group-sm">
                            <span class="input-group-addon" id="sizing-addon3">@</span>
                            <input type="text" class="form-control" placeholder="Email" aria-describedby="sizing-addon3" name="email">
                        </div>
                    </div>
                <?php else: ?>
                    <span style="color: #EEEEEE">Logged in as <?php echo $user->getUsrName(); ?></span>
                <?php endif; ?>
                <br>
                <div class="form-group">
                    <textarea class="form-control" rows="3" name="text" placeholder="Comment..."></textarea>
                </div>
                <button type="submit" class="btn btn-danger">Submit</button>
            </form>

            <hr>

            <!-- Posted Comments -->

            <!-- Comment -->
            <?php foreach($comments as $comment): ?>
                <div class="media">
                    <div class="media-left media-middle">
                        <img class="media-object" src="<?php echo $this->basePath('img/man.jpg'); ?>" alt="..." height="64px" width="64px">
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">
                            <?php
                            /*    if(!is_null($comment->getComUserId()) || $comment->getComUserId() != 0)
                                {
                                    echo $this->escapeHtml($comment->comUserId->getUsrName());
                                }
                            else{*/
                                echo $this->escapeHtml($comment->getComEmail());
                            //}

                            ?>
                        </h4>
                        <?php echo $this->escapeHtml($comment->getComText()) ?>
                    </div>
                </div>
            <?php endforeach; ?>


        </div>
        <div class="col-md-4">
            <div class="well">
                <h4>Tags</h4>
                <?php foreach ($article->tags as $tag): ?>
                       <div>
                           <span class="label label-default" style="float: left;margin-right: 2px;"><?php echo $tag->getTitle(); ?></span>
                       </div>
                <?php endforeach; ?>
                <br>
            </div>
            <div class="well">
                <h4><?php echo $article->star ?></h4>
                <img src="<?php echo $article->thumb ?>" alt="img">
            </div>
            <div class="well">
                <h4>Blog Categories</h4>
                    <div class="list-group">
                        <?php foreach($categories as $categorie): ?>
                            <a href="<?php echo $this->url('articleCategory', array('category' => $this->customTools($categorie['categorie']))); ?>" class="list-group-item">
                                <span class="badge"><?php echo $categorie['r'] ?></span>
                                <?php echo $categorie['categorie'] ?>
                            </a>
                        <?php endforeach; ?>
                    </div>
            </div>
            <div class="well">
                <h4>Last Articles</h4>
                    <?php foreach($last_articles as $last): ?>
                        <div class="media">
                            <a href="<?php echo $this->url('articleSlug', array('category' => $this->customTools($last->categorie), 'name' => $this->customTools($last->slug))); ?>" style="color:black;">
                            <div class="media-left media-middle">
                                    <img class="media-object" src="<?php echo $last->thumb ?>" alt="<?php echo $last->title ?>" style="height: 64px;width: auto">
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading"><?php echo $last->star ?></h4>
                                <p><?php echo $last->title ?></p>
                            </div>
                            </a>
                        </div>
                    <?php endforeach; ?>

            </div>

        </div>

    </div>

    <hr>