<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			Comments
		</h1>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<a href="<?php echo $this->url('admin/default', array('controller' => 'comment', 'action' => 'create')); ?>"><button class="btn btn-primary" type="button" ><i class="fa fa-plus-square"></i>Create</button></a>
	</div>
</div>
<br>
<div class="row">
	<div class="col-lg-12">
		<table class="table table-bordered">
			<tr>
				<th>#</th>
				<th>User Email</th>
				<th>Article Name</th>
				<th>Status</th>
				<th>Actions</th>
			</tr>
			<?php foreach ($rowset as $row) : ?>
				<tr>
					<td><?php  echo $row->getComId() ?></td>
					<td><?php  echo $this->escapeHtml($row->getComEmail()) ?></td>
					<td><?php  echo $this->escapeHtml($row->getComArticleId()) ?></td>
					<td><?php  echo $this->escapeHtml($row->getComStatus()) ?></td>
					<td><a href="<?php echo $this->url('admin/default', array('controller' => 'comment', 'action' => 'update', 'id' => $row->getComId())); ?>"><button class="btn btn-primary" type="button" ><i class="fa fa-edit"></i>Edit</button></a>
						<a href="<?php echo $this->url('admin/default', array('controller' => 'comment', 'action' => 'delete', 'id' => $row->getComId()));?>" onclick="return confirm('Do you rely want to delete the record;')"><button class="btn btn-danger" type="button"><i class="fa fa-trash"></i>Delete</button></a></td>
				</tr>
			<?php endforeach; ?>

		</table>
	</div>
</div>