<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/default', array('controller' => 'comment', 'action' => 'update', 'id' => $id)));
$form->prepare();
?>

<div class="row">
    <h1>Update a comment</h1>
    <?php echo $this->form()->openTag($form); ?>
    <div class="form-group">
        <?php echo $this->formRow($form->get('comText')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('comStatus')); ?>
    </div>
    <?php echo $this->formSubmit($form->get('submit')); ?>
    <?php echo $this->form()->closeTag(); ?>
</div>