<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			Logs
		</h1>
	</div>
</div>
<div class="row">
	<div class="col-lg-10 col-lg-offset-1">
	<table class="table table-bordered">
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Type</th>
			<th>Message</th>
		</tr>
		<?php foreach ($rowset as $row) : ?>
			<tr>
				<td><?php  echo $row->getId() ?></td>
				<td><?php  echo $this->escapeHtml($row->getUserId()) ?></td>
				<td><?php  echo $this->escapeHtml($row->getType()) ?></td>
				<td><?php  echo $this->escapeHtml($row->getMessage()) ?></td>
			</tr>
		<?php endforeach; ?>

	</table>
	</div>
</div>

