<div class="row">
    <div class="col-xs-12">
        <div class="main">
            <div class="row">
                <div class="col-xs-12 col-sm-8 col-sm-offset-1">
                    <div class="col-xs-8 col-sm-7">
                        <div class="row">
                            <h3>Connexion</h3>
                            <?php
                            $form = $this->form;
                            $form->setAttribute('action', $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'login')));
                            $form->prepare();

                            echo $this->form()->openTag($form);
                            ?>
                                <div class="form-group">
                                    <div class="col-md-8">
                                        <?php echo $this->formRow($form->get('username')); ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-8">
                                        <?php echo $this->formRow($form->get('password')); ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-0 col-md-8">
                                        <?php echo $this->formRow($form->get('rememberme')); ?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-0 col-md-8">
                                        <?php echo $this->formSubmit($form->get('submit')); ?>
                                        <a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'registration', 'action' => 'index'));?>"><?php echo $this->translate('Register'); ?></a> |
                                        <a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'registration', 'action' => 'forgotten-password'));?>"><?php echo $this->translate('Forgotten Password'); ?></a>
                                    </div>
                                </div>
                            <?php echo $this->form()->closeTag(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>