<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('PenetraBlog'. $this->translate('PenetraBlog'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/icon.jpg'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.min.css'))
                        ->prependStylesheet($this->basePath('css/style.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/script.js'), "text/javascript")
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">

                        <ul class="nav navbar-nav menu">
                            <div class="left">
                                <li class=""><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                            </div>
                            <div class="right">
                                <?php $user = $this->identity(); ?>
                                <?php if(!is_null($user)): ?>
                                    <?php if($user->getUsrlId() == 4): ?>
                                        <li class=""><a href="<?php echo $this->url('admin/default', array('controller' => 'index', 'action' => 'index')) ?>"><?php echo $this->translate('Admin') ?></a></li>
                                    <?php endif; ?>
                                    <li class=""><a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'logout')) ?>"><?php echo $this->translate('Logout') ?></a></li>
                                <?php else: ?>
                                    <li class=""><a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'registration', 'action' => 'index')); ?>"><?php echo $this->translate('Register') ?></a></li>
                                    <li class=""><a href="<?php echo $this->url('auth-doctrine/default', array('controller' => 'index', 'action' => 'login')); ?>"><?php echo $this->translate('Login') ?></a></li>
                                <?php endif; ?>
                            </div>
                        </ul>

                </div>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
        <script type="text/javascript">
            $(function() {
                $('img').css({
                    'filter': 'blur(8px)',
                    '-webkit-filter': 'blur(8px)',
                    '-moz-filter':'blur(8px)',
                    '-o-filter': 'blur(8px)',
                    '-ms-filter': 'blur(8px)',
                    }
                );
                $('iframe').css({
                        'filter': 'blur(50px)',
                        '-webkit-filter': 'blur(50px)',
                        '-moz-filter':'blur(50px)',
                        '-o-filter': 'blur(50px)',
                        '-ms-filter': 'blur(50px)',
                    }
                );

                $("select#stars , select#categories").change(function () {
                    console.log("1");
                    var star = $("#stars").val();
                    var cat = $("#categories").val();
                    var ajax_url = "<?= $this->url('admin/default', array('controller'=>'article', 'action'=>'videoSearch'));?>";
                    $.ajax({
                        type:"POST",
                        url: ajax_url,
                        dataType:   'json',
                        async:      true,
                        data: {
                            stars : star,
                            categories : cat
                        },
                        success: function(data){
                            if(data['success'] == true)
                            {
                                var videos = data['result']['videos'];
                                console.log(videos);
                                document.getElementById('videoSelect').options.length=0;
                                $.each(videos, function(key, value) {
                                    var video = value['video'];
                                    $('#videoSelect')
                                        .append($("<option></option>").attr("value",video['video_id']).text(video['title']));
                                });
                            }

                        }
                    });
                });
            });
        </script>
    </body>
</html>

