<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">
			Articles
		</h1>
	</div>
</div>
<div class="row">
	<div class="col-lg-12">
		<a href="<?php echo $this->url('admin/default', array('controller' => 'article', 'action' => 'create')); ?>"><button class="btn btn-primary" type="button" ><i class="fa fa-plus-square"></i>Create</button></a>
	</div>
</div>
<br>
<div class="row">
	<div class="col-lg-12">
		<table class="table table-bordered">
			<tr>
				<th>#</th>
				<th>Title</th>
				<th>Star</th>
				<th>Categorie</th>
				<th>Introduction</th>
				<th>Actions</th>
			</tr>
			<?php foreach ($rowset as $row) : ?>
				<tr>
					<td><?php  echo $row->getId() ?></td>
					<td><?php  echo $this->escapeHtml($row->getTitle()) ?></td>
					<td><?php  echo $this->escapeHtml($row->getStar()) ?></td>
					<td><?php  echo $this->escapeHtml($row->getCategorie()) ?></td>
					<td><?php  echo $this->escapeHtml($row->getIntroduction()) ?></td>
					<td><a href="<?php echo $this->url('admin/default', array('controller' => 'article', 'action' => 'update', 'id' => $row->getId())); ?>"><button class="btn btn-primary" type="button" ><i class="fa fa-edit"></i>Edit</button></a>
						<a href="<?php echo $this->url('admin/default', array('controller' => 'article', 'action' => 'delete', 'id' => $row->getId()));?>" onclick="return confirm('Do you rely want to delete the record;')"><button class="btn btn-danger" type="button"><i class="fa fa-trash"></i>Delete</button></a></td>
				</tr>
			<?php endforeach; ?>

		</table>
	</div>
</div>