<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/default', array('controller' => 'article', 'action' => 'update' ,  'id' => $id)));
$form->prepare();
?>
<div class="row">
    <h1>Update an article</h1>
    <?php echo $this->form()->openTag($form); ?>
    <div class="form-group">
        <?php echo $this->formRow($form->get('star')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('categorie')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('video')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('description')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('title')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('introduction')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('tagsInline')); ?>
    </div>
    <?php echo $this->formSubmit($form->get('submit')); ?>
    <?php echo $this->form()->closeTag(); ?>
</div>