<?php
$form = $this->form;
$form->setAttribute('action', $this->url('auth-doctrine/default', array('controller' => 'registration', 'action' => 'index')));
$form->prepare();
?>

<div class="row">
    <h1>Registration</h1>
    <?php echo $this->form()->openTag($form); ?>
    <div class="form-group">
        <?php echo $this->formRow($form->get('usrName')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('usrEmail')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('usrPassword')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('usrPasswordConfirm')); ?>
    </div>
    <div class="form-group">
        <?php echo $this->formRow($form->get('captcha')); ?>
    </div>
    <?php echo $this->formSubmit($form->get('submit')); ?>
    <?php echo $this->form()->closeTag(); ?>
</div>
