<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin/default', array('controller' => 'user', 'action' => 'create')));
$form->prepare();
?>

    <div class="row">
        <h1>Create an user</h1>
        <?php echo $this->form()->openTag($form); ?>
        <div class="form-group">
            <?php echo $this->formRow($form->get('usrName')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('usrEmail')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('usrPassword')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('usrlId')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('usrActive')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('usrEmailConfirmed')); ?>
        </div>
        <?php echo $this->formSubmit($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
    </div>

