<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Penetra Blog
            <small></small>
        </h1>
    </div>
    <!-- Blog Entries Column -->
    <div class="col-lg-9">

        <div class="row">
        <?php foreach ($articles as $article) : ?>
            <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
                <div class="thumbnail">
                    <img src="<?php echo $article->thumb ?>" alt="img">
                    <div class="caption">
                        <p><?php echo $article->introduction ?></p>
                        <p class="text-right"><a href="<?php echo $this->url('articleSlug', array('category' => $this->customTools($article->categorie), 'name' => $this->customTools($article->slug))); ?>"  role="button">Read</a>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
        </div>
    </div>

    <div class="col-md-3">
        <div class="well">
            <h4>Blog Categories</h4>
            <div class="row">
                <?php foreach($categories as $categorie) :?>
                    <div class="col-lg-6">
                        <ul class="list-unstyled">
                            <?php foreach ($categorie as $cat) :?>
                                <li>
                                    <a href="<?php echo $this->url('articleCategory', array('category' => $this->customTools($cat[1]))); ?>"><?php echo $cat[1] ?></a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>

    </div>

</div>